import {useEffect,useMemo,useState} from 'react';
import {AreaChart,Area,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,ReferenceLine} from 'recharts';
import {ArrowDownToLine,ArrowRight,ArrowUpRight,Database,FlaskConical,Layers3,Map as MapIcon,Plus,Play,Pause,Thermometer,CloudRain,Droplets,Wind,ChevronRight,Upload,CalendarDays} from 'lucide-react';
import {api,format,type Dataset,type Metadata,type Metric,type Analysis} from './api';
import {UkraineMap,type MapValues} from './UkraineMap';
import {WeatherLegend} from './weatherPalette';
import ImportWizard from './ImportWizard';
import DisastersPage from './DisastersPage';
import DisasterImport from './DisasterImport';
import {type DisasterCatalog} from './disasterTypes';

const metricIcons={temperature:Thermometer,precipitation:CloudRain,humidity:Droplets,wind:Wind};
const dateLabel=(d:string)=>new Date(d+'T00:00:00Z').toLocaleDateString('uk-UA',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});
function monthList(start:string,end:string){const out:string[]=[];let d=new Date(start.slice(0,7)+'-01T00:00:00Z');while(d.toISOString().slice(0,10)<=end){out.push(d.toISOString().slice(0,7));d.setUTCMonth(d.getUTCMonth()+1);}return out;}
function monthEnd(m:string){const [y,n]=m.split('-').map(Number);return new Date(Date.UTC(y,n,0)).toISOString().slice(0,10);}
export default function App(){
 const [meta,setMeta]=useState<Metadata|null>(null),[datasets,setDatasets]=useState<Dataset[]>([]),[selected,setSelected]=useState(''),[page,setPage]=useState('disasters');
 const [modal,setModal]=useState(false),[error,setError]=useState(''),[loadingSample,setLoadingSample]=useState(false);
 const [metric,setMetric]=useState<Metric>('temperature'),[region,setRegion]=useState('UA-46'),[start,setStart]=useState(''),[end,setEnd]=useState(''),[cursor,setCursor]=useState(''),[playing,setPlaying]=useState(false);
 const [analysis,setAnalysis]=useState<Analysis|null>(null),[mapValues,setMapValues]=useState<MapValues>({}),[pending,setPending]=useState(false),[mapPending,setMapPending]=useState(false);
 const [catalogs,setCatalogs]=useState<DisasterCatalog[]>([]),[emdatModal,setEmdatModal]=useState(false);

 async function refreshCatalogs(){setCatalogs(await api<DisasterCatalog[]>('/disaster-datasets'));}
 const [mapMode,setMapMode]=useState<'frame'|'period'>('frame');
 const dataset=datasets.find(d=>d.id===selected);const months=useMemo(()=>dataset?monthList(dataset.report.start,dataset.report.end):[],[dataset]);const activeMonths=months.filter(m=>m>=start.slice(0,7)&&m<=end.slice(0,7));
 async function refresh(id?:string){const data=await api<Dataset[]>('/datasets');setDatasets(data);if(id)setSelected(id);else setSelected(old=>data.some(d=>d.id===old)?old:data[0]?.id||'');}
 useEffect(()=>{Promise.all([api<Metadata>('/metadata'),refresh(),refreshCatalogs()]).then(([m])=>setMeta(m)).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!dataset)return;setStart(dataset.report.start);setEnd(dataset.report.end);setCursor(dataset.report.start.slice(0,7));setRegion(dataset.report.regions.includes('UA-46')?'UA-46':dataset.report.regions[0]);setMetric(dataset.report.variables[0]);setPlaying(false);},[selected]);
 useEffect(()=>{if(!activeMonths.includes(cursor)&&activeMonths.length)setCursor(activeMonths[0]);},[start,end,cursor,activeMonths.join(',')]);
 useEffect(()=>{if(!playing||!activeMonths.length)return;const t=setInterval(()=>setCursor(c=>activeMonths[(activeMonths.indexOf(c)+1)%activeMonths.length]),1000);return()=>clearInterval(t);},[playing,activeMonths.join(',')]);
 useEffect(()=>{if(!selected||!start||!end||start>end)return;const c=new AbortController();setPending(true);setAnalysis(null);const t=setTimeout(()=>{api<Analysis>(`/datasets/${selected}/analysis?`+new URLSearchParams({region,variable:metric,start,end}),{signal:c.signal}).then(setAnalysis).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!c.signal.aborted)setPending(false);});},140);return()=>{clearTimeout(t);c.abort();};},[selected,region,metric,start,end]);
 useEffect(()=>{if(!dataset||!cursor||!start||!end)return;const c=new AbortController();setMapPending(true);const frameStart=mapMode==='frame'?[cursor+'-01',start].sort().at(-1)!:start;const frameEnd=mapMode==='frame'?[monthEnd(cursor),end].sort()[0]:end;if(frameStart>frameEnd)return()=>c.abort();const t=setTimeout(()=>{api<MapValues>(`/datasets/${selected}/map?`+new URLSearchParams({variable:metric,start:frameStart,end:frameEnd}),{signal:c.signal}).then(setMapValues).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!c.signal.aborted)setMapPending(false);});},80);return()=>{clearTimeout(t);c.abort();};},[selected,metric,cursor,mapMode,start,end]);
 async function sample(){setLoadingSample(true);setError('');try{const r=await api<{id:string}>('/sample/import',{method:'POST'});await refresh(r.id);setPage('explore');}catch(e){setError((e as Error).message);}finally{setLoadingSample(false);}}
 useEffect(()=>setMapValues({}),[selected,metric]);
 const scale=useMemo<[number,number]>(()=>metric==='temperature'?[-15,35]:metric==='humidity'?[0,100]:metric==='wind'?[0,15]:[0,mapMode==='frame'?200:Math.max(200,Math.ceil(Math.max(0,...Object.values(mapValues).map(v=>v.value))/100)*100)],[metric,mapMode,mapValues]);
 const unit=meta?.variables[metric].unit||'';const stats=analysis?.stats;const Icon=metricIcons[metric];
 const query=new URLSearchParams({region,start,end});
 const ticks=months.filter((_,i)=>i===0||i===months.length-1||i%Math.max(1,Math.ceil(months.length/6))===0);
 return <><header className="topbar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('disasters');}}><span className="brand-icon"><Layers3 size={23}/></span>обрій</a><nav><button className={page==='disasters'?'nav-active':''} onClick={()=>setPage('disasters')}><FlaskConical size={17}/>Катастрофи<span className="nav-count">{catalogs.reduce((sum,c)=>sum+c.report.count,0)}</span></button><button className={page==='explore'?'nav-active':''} onClick={()=>setPage('explore')}><MapIcon size={17}/>Дослідження</button><button className={page==='datasets'?'nav-active':''} onClick={()=>setPage('datasets')}><Database size={17}/>Датасети<span className="nav-count">{datasets.length}</span></button><button className={page==='method'?'nav-active':''} onClick={()=>setPage('method')}><FlaskConical size={17}/>Методика</button></nav></header>
 <main><div className="page-heading"><div><h1>{page==='explore'?'Погода':page==='datasets'?'Датасети':page==='disasters'?'Катастрофи':'Методика'}</h1></div><div className="button-row page-actions"><button className="secondary" onClick={()=>setEmdatModal(true)}><Upload size={17}/>EM-DAT Excel</button><button className="primary" onClick={()=>setModal(true)}><Plus size={18}/>Завантажити CSV</button></div></div>
 {error&&<div role="alert" className="error">{error}<button className="text-btn" onClick={()=>setError('')}>Закрити</button></div>}
 {page==='explore'&&(!dataset?<section className="empty-hero"><div className="empty-art"><MapIcon size={78} strokeWidth={.8}/></div><div><h2>Додайте погодні дані</h2><div className="button-row"><button className="primary" onClick={sample} disabled={loadingSample}>{loadingSample?'Готуємо приклад…':'Відкрити приклад ERA5'}<ArrowRight size={18}/></button><button className="secondary" onClick={()=>setModal(true)}><Upload size={17}/>Власний CSV</button></div><small>Приклад — реаналіз для точок біля міст, а не середні по областях.</small></div></section>:<>
 <div className="dataset-strip"><Database size={18}/><select aria-label="Активний датасет" value={selected} onChange={e=>setSelected(e.target.value)}>{datasets.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select><span className="tag">{dataset.report.valid.toLocaleString('uk-UA')} записів</span><span className="tag">{dataset.report.regions.length} територій</span><button className="text-btn" onClick={()=>setPage('datasets')}>Про набір<ArrowUpRight size={15}/></button></div>
 <div className="workspace"><aside className="filter-panel"><h3>Показник</h3><div className="metric-options">{Object.entries(meta?.variables||{}).map(([key,v])=>{const I=metricIcons[key as Metric];return <button key={key} disabled={!dataset.report.variables.includes(key as Metric)} className={metric===key?'metric active':'metric'} onClick={()=>setMetric(key as Metric)}><I size={19}/><span>{v.label}</span><small>{v.unit}</small>{metric===key&&<ChevronRight size={14}/>}</button>;})}</div><label className="field-label">Територія<select aria-label="Область" value={region} onChange={e=>setRegion(e.target.value)}>{Object.entries(meta?.regions||{}).map(([code,name])=><option key={code} value={code}>{name}{!dataset.report.regions.includes(code)?' · немає даних':''}</option>)}</select></label><label className="field-label">Початок періоду<input type="date" aria-label="Початок періоду" min={dataset.report.start} max={end} value={start} onChange={e=>{if(e.target.value&&e.target.value<=end&&e.target.value>=dataset.report.start)setStart(e.target.value);}}/></label><label className="field-label">Кінець періоду<input type="date" aria-label="Кінець періоду" min={start} max={dataset.report.end} value={end} onChange={e=>{if(e.target.value&&e.target.value>=start&&e.target.value<=dataset.report.end)setEnd(e.target.value);}}/></label><p className="spatial-note">{dataset.spatial_kind==='point'?'Дані точки, не середнє по області.':'Дані області.'}</p><a className="export-link" href={`/api/datasets/${selected}/export?${query}`}><ArrowDownToLine size={17}/>Скачати вибірку CSV</a></aside>
 <section className="map-panel"><div className="panel-heading"><div><h3>{meta?.variables[metric].label} на карті</h3></div><div className="segmented"><button className={mapMode==='frame'?'selected':''} onClick={()=>setMapMode('frame')}>Місяць</button><button className={mapMode==='period'?'selected':''} onClick={()=>setMapMode('period')}>Увесь період</button></div></div><div className="map-frame"><div className="map-date"><CalendarDays size={14}/>{mapMode==='frame'?cursor:`${start} — ${end}`}<span>{metric==='precipitation'?'сума':'середнє'}</span>{mapPending&&<span>оновлення…</span>}</div>{meta&&<UkraineMap values={mapValues} metric={metric} selected={region} onSelect={setRegion} regions={meta.regions} unit={unit} scale={scale}/>}</div><div className="map-legend weather-map-legend"><WeatherLegend metric={metric} scale={scale} unit={unit} label={meta?.variables[metric].label||''}/><span className="nodata"><i/>Немає даних</span></div></section>
 <aside className="stats-panel"><h3>{meta?.regions[region]}</h3><p className="stats-period">{start&&dateLabel(start)} —<br/>{end&&dateLabel(end)}</p><div className="main-stat"><span>{metric==='precipitation'?'Сума за період':'Середнє за період'}</span><strong>{pending?'…':format(metric==='precipitation'?stats?.sum:stats?.mean)}<small>{unit}</small></strong><span className="stat-caption">{metric==='precipitation'&&stats&&stats.coverage<100?'Неповна сума: є пропущені дні':''}</span></div><div className="stat-pair"><div><span>Мінімум</span><b>{format(stats?.min)}<small>{unit}</small></b></div><div><span>Максимум</span><b>{format(stats?.max)}<small>{unit}</small></b></div></div></aside></div>
 <section className="timeline-panel"><button className="play-btn" aria-label={playing?'Зупинити анімацію':'Відтворити анімацію'} onClick={()=>{setMapMode('frame');setPlaying(!playing);}}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><div className="timeline-label"><strong>Таймлайн</strong><span>Місячний крок · {cursor}</span></div><div className="timeline-track"><input type="range" aria-label="Таймлайн" min="0" max={Math.max(0,activeMonths.length-1)} value={Math.max(0,activeMonths.indexOf(cursor))} onChange={e=>{setCursor(activeMonths[+e.target.value]);setPlaying(false);setMapMode('frame');}}/><div className="timeline-ticks">{ticks.map(m=><span key={m}>{m}</span>)}</div></div><span className="timeline-end">{activeMonths.length} міс.</span></section>
 <section className="chart-panel"><div className="panel-heading"><div><h3><Icon size={19}/>{meta?.variables[metric].label} · {meta?.regions[region]}</h3></div><span className="tag">{analysis?.resolution==='monthly'?'Місячні агрегати':'Добові значення'} · {unit}</span></div>{!analysis||!analysis.stats.count?<div className="chart-empty">{pending?'Розраховуємо часовий ряд…':'Немає даних у вибраному періоді'}</div>:<div className="chart"><ResponsiveContainer width="100%" height="100%">{metric==='precipitation'?<BarChart data={analysis.series}><CartesianGrid vertical={false} stroke="#e9ece6"/><XAxis dataKey="date" tickFormatter={d=>analysis.resolution==='monthly'?d.slice(0,7):d.slice(5)} minTickGap={40} tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false} width={42}/><Tooltip formatter={v=>[`${format(Number(v))} ${unit}`,'Опади']}/><Bar dataKey="value" fill="#609b87" radius={[2,2,0,0]}/><ReferenceLine x={cursor+'-01'} stroke="#d69445" strokeDasharray="4 3"/></BarChart>:<AreaChart data={analysis.series}><defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#46977b" stopOpacity={.24}/><stop offset="100%" stopColor="#46977b" stopOpacity={.01}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e9ece6"/><XAxis dataKey="date" tickFormatter={d=>analysis.resolution==='monthly'?d.slice(0,7):d.slice(5)} minTickGap={40} tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false} width={42}/><Tooltip formatter={v=>[`${format(Number(v))} ${unit}`,meta?.variables[metric].label]}/><Area type="linear" dataKey="value" stroke="#287b61" fill="url(#chartFill)" strokeWidth={1.8} dot={analysis.stats.count < 50 ? {r: 2, fill: '#287b61'} : false} connectNulls={false} isAnimationActive={false}/><ReferenceLine x={cursor+'-01'} stroke="#d69445" strokeDasharray="4 3"/></AreaChart>}</ResponsiveContainer></div>}<div className="chart-footer"><span><i/> {dataset.source}</span></div></section>
 </>)}
 {page==='disasters'&&<DisastersPage catalogs={catalogs} regions={meta?.regions||{}} onUpload={()=>setEmdatModal(true)}/>}
 {page==='datasets'&&<section className="datasets-page"><div className="section-title"><h2>Каталог наборів <span>{datasets.length}</span></h2><a href="/api/sample" className="secondary"><ArrowDownToLine size={16}/>Приклад CSV</a></div>{!datasets.length&&<p className="empty-message">Ще немає наборів. Завантажте CSV або додайте приклад нижче.</p>}<div className="dataset-cards">{datasets.map(d=><article className="dataset-card" key={d.id}><div className="dataset-card-top"><span className="dataset-icon"><Database size={22}/></span></div><h3>{d.name}</h3><p>{d.source}</p><div className="dataset-meta"><span>{d.report.start} — {d.report.end}</span><span>{d.report.valid.toLocaleString('uk-UA')} рядків · {d.report.regions.length} територій</span><span>{d.spatial_kind==='point'?'Точкові дані':'Регіональні дані'} · відхилено {d.report.invalid} рядків</span></div><div className="dataset-tags">{d.report.variables.map(v=><span className="tag" key={v}>{meta?.variables[v].label}</span>)}</div><div className="card-actions"><button className="text-btn" onClick={()=>{setSelected(d.id);setPage('explore');}}>Дослідити<ArrowRight size={16}/></button><a href={`/api/datasets/${d.id}/original`} title="Завантажити оригінал"><ArrowDownToLine size={18}/>CSV</a></div></article>)}<article className="sample-card"><FlaskConical size={26}/><h3>Приклад ERA5</h3><p>27 територій України</p><button className="secondary" disabled={loadingSample} onClick={sample}>{loadingSample?'Завантаження…':'Додати приклад'}<Plus size={16}/></button><a href="/api/sample/source" target="_blank" rel="noreferrer">Походження даних ↗</a></article></div></section>}
 {page==='method'&&<section className="method-grid"><article><h2>Розрахунки</h2><p>Температура, вологість і вітер — середнє; опади — сума за період. Мінімум і максимум — за добовими значеннями.</p><p>Пропуски не замінюються нулями.</p><p>Карта — вибраний місяць або період; калькулятор — увесь період. Ряди понад 1 500 днів групуються за місяцями.</p></article><article><h2>Джерела</h2><p>ERA5 / Open-Meteo, доба UTC. 27 територій, точки біля міст; не середні по областях.</p><a href="https://open-meteo.com/en/docs/historical-weather-api" target="_blank" rel="noreferrer">Open-Meteo · CC BY 4.0 ↗</a><p>Межі: geoBoundaries / OpenStreetMap / Wambacher, ODbL.</p><a href="/boundaries-source.json" target="_blank" rel="noreferrer">Метадані меж ↗</a></article><article><h2>Імпорт</h2><p>CSV UTF-8, до 20 МБ і 1 000 000 рядків. Обов’язкові дата, область та показник; один рядок на область за день.</p><p>Одиниці: K → °C, м → мм, частка → %, км/год → м/с. Помилки й дублікати — у звіті. Файли зберігаються локально.</p></article><article><h2>Катастрофи</h2><p>Excel EM-DAT / CRED. Подія в кількох областях рахується один раз. «—» — невідомі наслідки; збитки — номінальні USD.</p><p>Графік — рік початку; карта — події, що тривали у вибраному році. Позначки без координат розміщено в центрі області.</p></article></section>}

 </main>{emdatModal&&<DisasterImport onClose={()=>setEmdatModal(false)} onImported={()=>{setEmdatModal(false);refreshCatalogs().then(()=>setPage('disasters')).catch(e=>setError(e.message));}}/>}{modal&&<ImportWizard onClose={()=>setModal(false)} onImported={id=>{setModal(false);refresh(id).then(()=>setPage('explore')).catch(e=>setError(e.message));}}/>}</>;
}
