import {useState,useRef} from 'react';
import {UploadCloud,X,ArrowRight,FileSpreadsheet} from 'lucide-react';
import {api,post} from './api';
export default function DisasterImport({onClose,onImported}:{onClose:()=>void;onImported:(id:string)=>void}){
 const input=useRef<HTMLInputElement>(null);const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const [preview,setPreview]=useState<{token:string;filename:string;report:{count:number;start:string;end:string;region_count:number;unlocated:number;incomplete_dates:number;errors:{row:number;reason:string}[]}}|null>(null);
 const [name,setName]=useState('Катастрофи України · EM-DAT'),[skip,setSkip]=useState(false);
 async function upload(file?:File){if(!file)return;setError('');setBusy(true);try{const form=new FormData();form.append('file',file);setPreview(await api('/disaster-uploads',{method:'POST',body:form}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function commit(){if(!preview)return;setBusy(true);try{const r=await api<{id:string}>(`/disaster-uploads/${preview.token}/commit`,post({name,skip_invalid:skip}));onImported(r.id);}catch(e){setError((e as Error).message);setBusy(false);}}
 return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="emdat-title"><div className="modal-heading"><div><h2 id="emdat-title">Імпорт каталогу катастроф</h2></div><button className="icon-btn" aria-label="Закрити імпорт EM-DAT" onClick={onClose} disabled={busy}><X size={20}/></button></div>{error&&<div className="error" role="alert">{error}</div>}{!preview?<div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();upload(e.dataTransfer.files[0]);}}><UploadCloud size={40}/><h3>Завантажте Excel з EM-DAT</h3><p>public_emdat…xlsx · до 20 МБ</p><button className="primary" disabled={busy} onClick={()=>input.current?.click()}>{busy?'Перевіряємо…':'Вибрати Excel'}</button><input ref={input} hidden type="file" accept=".xlsx" onChange={e=>upload(e.target.files?.[0])}/></div>:<><div className="file-line"><FileSpreadsheet size={20}/>{preview.filename}</div><label className="field-label">Назва каталогу<input value={name} onChange={e=>setName(e.target.value)}/></label><div className="validation success"><h3>Файл перевірено</h3><p>{preview.report.count} унікальних подій в Україні · {preview.report.start} — {preview.report.end}</p><p>{preview.report.region_count} територій · {preview.report.unlocated} подій без визначеної області · {preview.report.incomplete_dates} неповних дат</p></div>{preview.report.errors.length>0&&<div className="validation warning">{preview.report.errors.map(e=><p key={e.row}>Рядок {e.row}: {e.reason}</p>)}<label className="checkbox"><input type="checkbox" checked={skip} onChange={e=>setSkip(e.target.checked)}/>Пропустити помилкові записи</label></div>}<div className="modal-footer"><button className="text-btn" onClick={()=>setPreview(null)}>Інший файл</button><button className="primary" onClick={commit} disabled={busy||!name.trim()||(preview.report.errors.length>0&&!skip)}>{busy?'Імпорт…':'Імпортувати катастрофи'}<ArrowRight size={16}/></button></div></>}</section></div>;
}
