import {useRef,useState} from 'react';
import {UploadCloud,ArrowRight,CheckCircle2,FileSpreadsheet,X,Download,AlertTriangle} from 'lucide-react';
import {api,post,downloadBlob, type Preview,type Report,type Config} from './api';

const fields:Record<string,string>={date:'Дата *',region:'Область *',temperature:'Температура',precipitation:'Опади',humidity:'Вологість',wind:'Вітер'};
const units:Record<string,[string,string][]>= {temperature:[['C','°C'],['K','K']],precipitation:[['mm','мм'],['m','м']],humidity:[['percent','%'],['fraction','0–1']],wind:[['ms','м/с'],['kmh','км/год']]};
export default function ImportWizard({onClose,onImported}:{onClose:()=>void;onImported:(id:string)=>void}){
 const input=useRef<HTMLInputElement>(null); const [preview,setPreview]=useState<Preview|null>(null); const [report,setReport]=useState<Report|null>(null); const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const [config,setConfig]=useState<Config>({name:'',source:'Власний CSV',spatial_kind:'regional',mapping:{},units:{temperature:'C',precipitation:'mm',humidity:'percent',wind:'ms'},date_format:'iso',skip_invalid:false});
 async function upload(file?:File){if(!file)return;setBusy(true);setError('');try{const form=new FormData();form.append('file',file);const result=await api<Preview>('/uploads',{method:'POST',body:form});setPreview(result);setConfig(c=>({...c,name:file.name.replace(/\.csv$/i,''),mapping:result.mapping}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function change(next:Partial<Config>){setConfig(c=>({...c,...next}));setReport(null);}
 async function validate(){if(!preview)return;setBusy(true);setError('');try{setReport(await api<Report>(`/uploads/${preview.token}/validate`,post(config)));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function commit(){if(!preview)return;setBusy(true);setError('');try{const result=await api<{id:string}>(`/uploads/${preview.token}/commit`,post(config));onImported(result.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function errors(){if(!preview)return;try{const r=await fetch(`/api/uploads/${preview.token}/errors`,post(config));if(!r.ok)throw new Error('Не вдалося експортувати помилки');downloadBlob(await r.blob(),'import-errors.csv');}catch(e){setError((e as Error).message);}}
 return <div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!busy)onClose();}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="import-title"><div className="modal-heading"><div><h2 id="import-title">Імпорт датасету</h2></div><button className="icon-btn" aria-label="Закрити імпорт" onClick={onClose} disabled={busy}><X size={20}/></button></div>
 <div className="steps"><span className="active">1. Файл</span><i/><span className={preview?'active':''}>2. Колонки</span><i/><span className={report?'active':''}>3. Перевірка</span></div>
 {error&&<div role="alert" className="error"><AlertTriangle size={18}/>{error}</div>}
 {!preview?<><div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();upload(e.dataTransfer.files[0]);}}><UploadCloud size={42}/><h3>Перетягніть CSV сюди</h3><p>Добові дані · до 20 МБ · UTF-8</p><button className="primary" disabled={busy} onClick={()=>input.current?.click()}>{busy?'Читаємо файл…':'Вибрати файл'}</button><input ref={input} hidden type="file" accept=".csv" onChange={e=>upload(e.target.files?.[0])}/></div><div className="helper"><FileSpreadsheet size={20}/><div><strong>Один рядок — одна область за один день</strong><p>Дата, область і показник; роздільник — кома, «;» або табуляція.</p><a href="/api/sample" download>Приклад CSV</a></div></div></>:<>
 <div className="file-line"><FileSpreadsheet size={22}/><strong>{preview.filename}</strong><span>{preview.total.toLocaleString('uk-UA')} рядків</span><button className="text-btn" onClick={()=>{setPreview(null);setReport(null);}}>Змінити файл</button></div>
 <div className="form-grid"><label>Назва набору<input value={config.name} onChange={e=>change({name:e.target.value})}/></label><label>Джерело<input value={config.source} onChange={e=>change({source:e.target.value})}/></label><label>Географічний зміст<select value={config.spatial_kind} onChange={e=>change({spatial_kind:e.target.value})}><option value="regional">Показники області</option><option value="point">Одна точка в області / місті</option></select></label><label>Формат дати<select value={config.date_format} onChange={e=>change({date_format:e.target.value})}><option value="iso">РРРР-ММ-ДД</option><option value="dmy">ДД.ММ.РРРР</option></select></label></div>
 <h3>Зіставте колонки</h3><div className="mapping">{Object.entries(fields).map(([key,title])=><div className="mapping-row" key={key}><span>{title}</span><ArrowRight size={15}/><select aria-label={`Колонка: ${title}`} value={config.mapping[key]||''} onChange={e=>change({mapping:{...config.mapping,[key]:e.target.value}})}><option value="">Не використовувати</option>{preview.headers.map(h=><option key={h}>{h}</option>)}</select>{units[key]&&<select aria-label={`Одиниці: ${title}`} value={config.units[key]} onChange={e=>change({units:{...config.units,[key]:e.target.value}})}>{units[key].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>}</div>)}</div>
 <details><summary>Попередній перегляд файлу</summary><div className="table-scroll"><table><thead><tr>{preview.headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{preview.preview.map((r,i)=><tr key={i}>{preview.headers.map(h=><td key={h}>{r[h]}</td>)}</tr>)}</tbody></table></div></details>
 {report&&<div className={'validation '+(report.invalid?'warning':'success')}><h3><CheckCircle2 size={19}/> Перевірку завершено</h3><p><b>{report.valid}</b> коректних · <b>{report.invalid}</b> відхилених · <b>{report.regions.length}</b> територій</p><p>{report.start} — {report.end}</p>{Object.entries(report.missing).some(([,v])=>v>0)&&<p>Пропуски збережено: {Object.entries(report.missing).filter(([,v])=>v>0).map(([k,v])=>`${fields[k]}: ${v}`).join(', ')}</p>}{report.errors.length>0&&<><ul>{report.errors.slice(0,5).map(e=><li key={e.row}>Рядок {e.row}: {e.reason}</li>)}</ul><button className="text-btn" onClick={errors}><Download size={15}/> Звіт про всі помилки</button><label className="checkbox"><input type="checkbox" checked={config.skip_invalid} onChange={e=>setConfig(c=>({...c,skip_invalid:e.target.checked}))}/>Імпортувати коректні записи, пропустивши {report.invalid} помилкових</label></>}</div>}
 <div className="modal-footer">{report?<button className="primary" onClick={commit} disabled={busy||!report.valid||(report.invalid>0&&!config.skip_invalid)}>{busy?'Імпортуємо…':'Імпортувати й відкрити'}<ArrowRight size={17}/></button>:<button className="primary" onClick={validate} disabled={busy||!config.name.trim()}>{busy?'Перевіряємо…':'Перевірити дані'}<ArrowRight size={17}/></button>}</div>
 </>}
 </section></div>;
}
